#ifndef PSPUTILITY_SYSPARAM_H
#define PSPUTILITY_SYSPARAM_H
#include "psp_compat.h"
#define PSP_SYSTEMPARAM_ID_INT_LANGUAGE 1
#define PSP_SYSTEMPARAM_ID_INT_TIMEZONE 2
#define PSP_SYSTEMPARAM_ID_INT_DAYLIGHTSAVINGS 3
#define PSP_SYSTEMPARAM_LANGUAGE_ENGLISH 1
#define PSP_SYSTEMPARAM_LANGUAGE_CHINESE_SIMPLIFIED 2
#define PSP_SYSTEMPARAM_DAYLIGHTSAVINGS_STD 0
#define PSP_SYSTEMPARAM_DAYLIGHTSAVINGS_SAVING 1
static inline int sceUtilityGetSystemParamInt(int id, int *res) { (void)id; if (res) *res = 1; return 0; }
#endif
